/* Generated By:JavaCC: Do not edit this line. VerificationScriptGrammarTreeConstants.java Version 5.0 */
package verser.server.compiler.implementations.jj;

public interface VerificationScriptGrammarTreeConstants
{
  public int JJTIDENTIFIER = 0;
  public int JJTINTEGER = 1;
  public int JJTSTRING = 2;
  public int JJTTYPE = 3;
  public int JJTVOID = 4;
  public int JJTINTEGERLITERAL = 5;
  public int JJTALLLITERAL = 6;
  public int JJTIDENTIFIERLIST = 7;
  public int JJTTYPELIST = 8;
  public int JJTTYPEDECLARATION = 9;
  public int JJTINTEGERLITERALLIST = 10;
  public int JJTALLLITERALLIST = 11;
  public int JJTCAPABILITYDECLARATION = 12;
  public int JJTADDITIVE = 13;
  public int JJTSIMPLEEXPRESSION = 14;
  public int JJTRELATION = 15;
  public int JJTLOGIC = 16;
  public int JJTRELATIONEXPRESSION = 17;
  public int JJTEXPRESSION = 18;
  public int JJTARRAYALLINNODE = 19;
  public int JJTARRAYINTEGERINNODE = 20;
  public int JJTARRAYOUTNODE = 21;
  public int JJTCAPABILITYNODE = 22;
  public int JJTIDENTIFIERFLOWSTATEMENT = 23;
  public int JJTARRAYOUTNODEFLOWSTATEMENT = 24;
  public int JJTFLOWSTATEMENT = 25;
  public int JJTSTATEMENTBLOCK = 26;
  public int JJTIFSTATEMENT = 27;
  public int JJTWHILESTATEMENT = 28;
  public int JJTSTATEMENT = 29;
  public int JJTVERIFICATIONBLOCK = 30;
  public int JJTVERIFICATIONSCRIPT = 31;


  public String[] jjtNodeName = {
    "Identifier",
    "Integer",
    "String",
    "Type",
    "Void",
    "IntegerLiteral",
    "AllLiteral",
    "IdentifierList",
    "TypeList",
    "TypeDeclaration",
    "IntegerLiteralList",
    "ALLLiteralList",
    "CapabilityDeclaration",
    "Additive",
    "SimpleExpression",
    "Relation",
    "Logic",
    "RelationExpression",
    "Expression",
    "ArrayALLInNode",
    "ArrayIntegerInNode",
    "ArrayOutNode",
    "CapabilityNode",
    "IdentifierFlowStatement",
    "ArrayOutNodeFlowStatement",
    "FlowStatement",
    "StatementBlock",
    "IfStatement",
    "WhileStatement",
    "Statement",
    "VerificationBlock",
    "VerificationScript",
  };
}
/* JavaCC - OriginalChecksum=b98cd855e264453f9bb32aa0f2fc1618 (do not edit this line) */
