/* Generated By:JavaCC: Do not edit this line. VerificationScriptGrammarVisitor.java Version 5.0 */
package verser.server.compiler.implementations.jj;

public interface VerificationScriptGrammarVisitor
{
  public VisitorResult visit(SimpleNode node, Object data);
  public VisitorResult visit(VS_Identifier node, Object data);
  public VisitorResult visit(VS_Integer node, Object data);
  public VisitorResult visit(VS_String node, Object data);
  public VisitorResult visit(VS_Type node, Object data);
  public VisitorResult visit(VS_Void node, Object data);
  public VisitorResult visit(VS_IntegerLiteral node, Object data);
  public VisitorResult visit(VS_AllLiteral node, Object data);
  public VisitorResult visit(VS_IdentifierList node, Object data);
  public VisitorResult visit(VS_TypeList node, Object data);
  public VisitorResult visit(VS_TypeDeclaration node, Object data);
  public VisitorResult visit(VS_IntegerLiteralList node, Object data);
  public VisitorResult visit(VS_ALLLiteralList node, Object data);
  public VisitorResult visit(VS_CapabilityDeclaration node, Object data);
  public VisitorResult visit(VS_Additive node, Object data);
  public VisitorResult visit(VS_SimpleExpression node, Object data);
  public VisitorResult visit(VS_Relation node, Object data);
  public VisitorResult visit(VS_Logic node, Object data);
  public VisitorResult visit(VS_RelationExpression node, Object data);
  public VisitorResult visit(VS_Expression node, Object data);
  public VisitorResult visit(VS_ArrayALLInNode node, Object data);
  public VisitorResult visit(VS_ArrayIntegerInNode node, Object data);
  public VisitorResult visit(VS_ArrayOutNode node, Object data);
  public VisitorResult visit(VS_CapabilityNode node, Object data);
  public VisitorResult visit(VS_IdentifierFlowStatement node, Object data);
  public VisitorResult visit(VS_ArrayOutNodeFlowStatement node, Object data);
  public VisitorResult visit(VS_FlowStatement node, Object data);
  public VisitorResult visit(VS_StatementBlock node, Object data);
  public VisitorResult visit(VS_IfStatement node, Object data);
  public VisitorResult visit(VS_WhileStatement node, Object data);
  public VisitorResult visit(VS_Statement node, Object data);
  public VisitorResult visit(VS_VerificationBlock node, Object data);
  public VisitorResult visit(VS_VerificationScript node, Object data);
}
/* JavaCC - OriginalChecksum=e7a227b742d8b9ac67ad60ab215ab1d6 (do not edit this line) */
