/* Generated By:JJTree: Do not edit this line. VS_ALLLiteralList.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=VS_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package verser.server.compiler.implementations.jj;

public
class VS_ALLLiteralList extends SimpleNode {
  public VS_ALLLiteralList(int id) {
    super(id);
  }

  public VS_ALLLiteralList(VerificationScriptGrammar p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public VisitorResult jjtAccept(VerificationScriptGrammarVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=3c16229a5e098d7db57ae00a82eb2e8c (do not edit this line) */
