/* Generated By:JJTree: Do not edit this line. VS_CapabilityDeclaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=VS_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package verser.server.compiler.implementations.jj;

public
class VS_CapabilityDeclaration extends SimpleNode {
  public VS_CapabilityDeclaration(int id) {
    super(id);
  }

  public VS_CapabilityDeclaration(VerificationScriptGrammar p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public VisitorResult jjtAccept(VerificationScriptGrammarVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=2ee7ec0c24314489a724dcdd2176f8be (do not edit this line) */
