/* Generated By:JJTree: Do not edit this line. VS_IdentifierFlowStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=VS_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package verser.server.compiler.implementations.jj;

public
class VS_IdentifierFlowStatement extends SimpleNode {
  public VS_IdentifierFlowStatement(int id) {
    super(id);
  }

  public VS_IdentifierFlowStatement(VerificationScriptGrammar p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public VisitorResult jjtAccept(VerificationScriptGrammarVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=71dcb6d85acb9674fe58dee7354df1ee (do not edit this line) */
