/* Generated By:JJTree: Do not edit this line. VS_IntegerLiteralList.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=VS_,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package verser.server.compiler.implementations.jj;

public
class VS_IntegerLiteralList extends SimpleNode {
  public VS_IntegerLiteralList(int id) {
    super(id);
  }

  public VS_IntegerLiteralList(VerificationScriptGrammar p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public VisitorResult jjtAccept(VerificationScriptGrammarVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=7f12b949184646cf363966dd7b751daf (do not edit this line) */
